RM 1.4.1 support

diff --git a/rbl-reinstall b/rbl-reinstall
--- a/rbl-reinstall
+++ b/rbl-reinstall
@@ -1,287 +1,274 @@
-#!/bin/bash
+#!/usr/bin/env ruby
 
-GEMSET=`rvm-prompt g | sed -e 's/@//'`
-RUBY=`rvm-prompt v | sed -e 's/\.[0-9]*$//'`
-if [ -z "$GEMSET" ]; then
-  echo "No gemset"
+require 'rubygems'
+require 'optparse'
+require 'yaml'
+
+def error(msg)
+  puts "echo #{msg}\n"
   exit
-fi
+end
 
-CONFIG="$( cd "$( dirname "$0" )" && pwd )"
-CONFIG="$CONFIG/rbl-reinstall.rc"
-export RAILS_ENV=development
+class Script
+  def initialize
+    @script = ''
+  end
 
-if [ ! -f $CONFIG ]; then
-    echo "$CONFIG does not exist"
-    exit
-fi
-
-source $CONFIG
-
-function fixgemspecs {
-  gemspecs=`ls -A /home/hnse/.rvm/gems/ruby-1.8.7-p358@redmine/specifications | tail -1 | wc -l`
-  if [ "$gemspecs" = "1" ]; then
-    for gemspec in `gem environment gemdir`/specifications/*.gemspec; do
-      ruby -pi -e "gsub(/s.date\s*=\s*%q\{([0-9]{4}-[0-9]{2}-[0-9]{2}) 00:00:00.0+Z?\}/, 's.date = %q{\1}')" $gemspec
-    done
-  fi
-}
-
-
-if [ -z "$DBROOTPW" ]; then
-    echo "DBROOTPW not set"
-    exit
-fi
-if [ -z "$DBPW" ]; then
-    echo "DBPW not set"
-    exit
-fi
-if [ -z "$DBUSER" ]; then
-    echo "DBUSER not set, defaulting to redmine"
-    DBUSER=redmine
-fi
-
-if [ ! -d ~/redmine ]; then
-    echo "~/redmine does not exist"
-    exit
-fi
-
-cd ~/redmine
-
-if [ ! -f ~/redmine/setup/database-redmine.yml ]; then
-    echo "~/redmine/setup/database-redmine.yml does not exist"
-    if [ "$GEMSET" = "redmine" ]; then
-        exit
-    fi
-fi
-if [ ! -f ~/redmine/setup/database-chiliproject.yml ]; then
-    echo "~/redmine/setup/database-chiliproject.yml does not exist"
-    if [ "$GEMSET" = "chiliproject" ]; then
-        exit
-    fi
-fi
-
-if [ ! -d ~/redmine/redmine_backlogs ]; then
-    echo "~/redmine/redmine_backlogs does not exist"
-    exit
-fi
-
-# ruby env
-if [ -z "`gem list | grep rails`" ]; then
-  RVM=y
-fi
-if [ -z "$RVM" ]; then
-  read -p "Reinstall RVM? " RVM
-fi
-if [[ $RVM =~ [Yy] ]]; then
-    echo "re-creating $GEMSET"
-    rvm --force gemset empty $GEMSET
-
-    if [[ "$GEMSET" = "redmine" ]]; then
-
-      echo 'Downgrading rubygems'
-      rvm rubygems latest-1.8
-
-      echo 'Installing base gems'
-      gem install rack -v=1.1.1
-      gem install rails -v=2.3.14
-      gem install i18n -v=0.4.2
-
-      echo 'Installing gems for redmine-backlogs'
-      gem install icalendar
-
-      gem install prawn
-      gem install holidays
-      gem install open-uri-cached
-      gem install nokogiri
-
-      # dev & testing
-      #gem install gherkin -v=2.8.0
-      gem install term-ansicolor -v=1.0.6
-      #gem install zentest-without-autotest
-      gem install rubyzip -v=0.9.5
-
-      gem install ZenTest -v=4.6.0
-      gem install -v=1.3.1 rspec
-      gem install -v=0.3.2 cucumber-rails
-      gem install -v=1.1.8 cucumber
-      gem install -v=0.2.15 culerity
-
-      gem install capybara -v=1.1.1
-      gem install spork # -v=0.8.5
-      gem install database_cleaner
-      #gem install autotest-rails
-      gem install redgreen
-      gem install -v=1.3.3 rspec-rails
-      gem install timecop
-      gem install thin
-
-      # cucumber-rails pulls in an unnecesary gherkin
-      #eval `ruby -e "require 'rubygems'; puts Gem.source_index.find_name('gherkin').reject{|x| x.version.version == '2.8.0'}.collect{|x| \"gem uninstall gherkin -v=#{x.version.version}\"}.join(\"\n\")"`
-
-      gem uninstall cucumber -v=1.1.8
-      gem uninstall gherkin -v=2.8.0
-      gem uninstall holidays -v=1.0.3
-      #gem uninstall rack -v=1.1.1
-
-      DUPLICATES=`gem list | grep , | wc -l`
-      if [[ "$DUPLICATES" != "0" ]]; then
-        echo 'Duplicate gems'
-        gem list | grep ,
-        exit
-      fi
-    fi
-
-    gem install bundler
-    bundle config build.mysql --with-mysql-config=`which mysql_config`
-    gem install mysql
-
-    if [[ "$RUBY" = "1.8" ]]; then
-      gem install system_timer
-      gem install rcov
+  def method_missing(meth, *args, &block)
+    qmeth = (meth.to_s + '?').intern
+    if Options.respond_to?(qmeth)
+      self << args[0] if Options.send(qmeth)
     else
-      gem install simplecov
-    fi
-fi
+      super
+    end
+  end
 
-# redmine
-if [ "$GEMSET" = "redmine" ]; then
-  if [ ! -f ~/redmine/redmine/config/database.yml ]; then
-    echo Forced RM install
-    RMINSTALL=Y
-  elif [ -z "$RMINSTALL" ]; then
-    read -p "Reinstall Redmine? " RMINSTALL
-  fi
-  if [[ $RMINSTALL =~ [Yy] ]]; then
-    if [ -z "$RMVERSION" ]; then
-      echo "VERSION not set"
+  def <<(line)
+    @script << "#{line}\n"
+  end
+
+  def gem(name, version=nil)
+    return unless Options.rvm?
+
+    if name.is_a?(String)
+      self << name
+      return
+    end
+
+    name = name.to_s
+
+    if version && version =~ /^-/
+      action = 'uninstall'
+      version.gsub!(/^-/, '')
+    else
+      action = 'install'
+    end
+    name << " -v=#{version}" if version
+
+    self << "gem #{action} #{name}"
+  end
+
+  def chiliproject(line)
+    self << line if Options.platform == 'chiliproject'
+  end
+  def redmine(line)
+    self << line if Options.platform == 'redmine'
+  end
+
+  def to_s
+    return @script
+  end
+end
+
+script = Script.new
+
+def exists(path)
+  return File.exist?(File.expand_path(path))
+end
+def verify(path)
+  error("#{path} does not exist") unless exists(path)
+end
+
+class Options
+  OPTIONSFILE = File.join(File.dirname(__FILE__), File.basename(__FILE__, File.extname(__FILE__)) + '.yml')
+  @@options = {}
+  @@options = YAML::load_file(OPTIONSFILE) if File.exist?(OPTIONSFILE)
+
+  OPTPARSE = OptionParser.new do |opts|
+    # Set a banner, displayed at the top
+    # of the help screen.
+    opts.banner = "Usage: rbl-reinstall [options] file1 file2 ..."
+ 
+    opts.on('-p', '--platform PLATFORM', 'Install platform' ) do |platform|
+    end
+
+    opts.on( '-i', '--install', 'DB root password' ) do
+      @@options[:install] = true
+    end
+
+    opts.on( '-r', '--rvm', 'Re-create rvm gemset' ) do
+      @@options[:rvm] = true
+    end
+
+    opts.on( '-R', '--rootpw PASSWORD', 'DB root password' ) do |pw|
+      @@options[:rootpw] = pw
+    end
+
+    @@options[:user] ||= 'redmine'
+    opts.on( '-U', '--user USER', 'DB user' ) do |user|
+      @@options[:user] = user
+    end
+    opts.on( '-P', '--pw PASSWORD', 'DB password' ) do |pw|
+      @@options[:pw] = pw
+    end
+
+    opts.on( '-a', '--admin PASSWORD', 'Admin password' ) do |pw|
+      @@options[:admin] = pw
+    end
+
+    opts.on( '-d', '--database', 'Re-install database' ) do
+      @@options[:database] = true
+    end
+
+    opts.on( '-v', '--version VERSION', 'Re-install database' ) do |version|
+    end
+
+    # This displays the help screen, all programs are
+    # assumed to have this option.
+    opts.on( '-h', '--help', 'Display this screen' ) do
+      puts opts
+      exit
+    end
+  end
+
+  OPTPARSE.top.each_option do |opt|
+    next unless opt.long && opt.long.is_a?(Array)
+    case opt.class.to_s
+      when 'OptionParser::Switch::RequiredArgument'
+        postfix=''
+      when 'OptionParser::Switch::NoArgument'
+        postfix='?'
+      else
+        raise "Unhandled class #{opt.class}"
+    end
+
+    switch = opt.long[0].gsub(/^-*/, '')
+    eval <<-ACCESSOR
+      def self.#{switch}#{postfix}
+        return @@options[:#{switch}]
+      end
+    ACCESSOR
+  end
+
+  OPTPARSE.parse!
+
+  @@options[:platform] = `rvm-prompt g | sed -e 's/@//'`.gsub(/[\r\n]/, '').strip
+  @@options[:version] = case @@options[:platform] when 'redmine' then '1.4.1' when 'chiliproject' then '2.6.0' else nil end
+
+  error("No platform selected") if @@options[:platform].to_s == ''
+  error("Unsupported platform #{@@options[:platform].inspect}") unless ['redmine', 'chiliproject'].include?(@@options[:platform])
+  error("Version not set") if Options.version.to_s == '' && Options.install?
+
+  @@options[@@options[:platform].intern].each_pair{|k, v| @@options[k] = v if @@options[k].to_s == ''} if @@options[@@options[:platform].intern].is_a?(Hash)
+
+  [:rvm, :install, :database].each{|option|
+    @@options[option] = nil if @@options[option].to_s.strip == ''
+    @@options[option] = (@@options[option].to_s.strip == 'true') if @@options[option].nil?
+  }
+
+  @@options[:install] ||= !exists("~/redmine/#{@@options[:platform]}/config/database.yml")
+  @@options[:rvm] ||= (`rvm list | grep rails` == '')
+
+  error("DB root password not set") if Options.rootpw.to_s == '' && Options.database?
+  error("DB password not set") if Options.pw.to_s == '' && Options.database?
+  error("DB user not set") if Options.pw.to_s == '' && Options.database?
+
+  verify('~/redmine')
+  verify("~/redmine/setup/database-#{Options.platform}.yml")
+  verify("~/redmine/redmine_backlogs")
+end
+
+
+script << 'echo "*** PIPE OUTPUT OF THIS SCRIPT THROUGH BASH ***"'
+script << 'set -e'
+script << 'export RAILS_ENV=development'
+script << 'cd ~/redmine'
+
+script.install "rm -rf ~/redmine/#{Options.platform}"
+script.install "cd ~/redmine"
+
+script.redmine "svn co http://redmine.rubyforge.org/svn/tags/#{Options.version} redmine"
+script.chiliproject "git clone http://github.com/chiliproject/chiliproject.git"
+script.chiliproject "cd ~/redmine/chiliproject"
+script.chiliproject "git fetch --tags"
+script.chiliproject "git checkout v#{Options.version}"
+
+script.install "cd ~/redmine/#{Options.platform}"
+script.install "ln -s ~/redmine/redmine_backlogs ~/redmine/#{Options.platform}/vendor/plugins"
+script.install "ln -s ~/redmine/redmine_backlogs/features ~/redmine/#{Options.platform}"
+script.install "cp ~/redmine/setup/database-#{Options.platform}.yml ~/redmine/#{Options.platform}/config/database.yml"
+script.install "echo rvm use `rvm-prompt v g` > ~/redmine/#{Options.platform}/.rvmrc"
+script.install "sed -i -e\"s/gem 'capybara'/gem 'capybara', '=0.3.9'/\" Gemfile"
+
+script.rvm "rvm --force gemset empty #{Options.platform}"
+
+script.rvm 'rvm rubygems latest-1.8'
+
+script.rvm "touch ~/redmine/redmine_backlogs/Gemfile.dev"
+script.rvm "touch ~/redmine/#{Options.platform}/Gemfile.dev"
+
+script.gem :rack, '1.1.1'
+script.gem :rails, '2.3.14'
+script.gem :i18n, '0.4.2'
+
+script.gem :icalendar
+script.gem :prawn
+script.gem :holidays , '1.0.3'
+script.gem :'open-uri-cached'
+script.gem :nokogiri
+
+# dev & testing
+#script.gem :gherkin, '2.6.2'
+script.gem :'term-ansicolor', '1.0.7'
+script.gem :rubyzip, '0.9.7'
+
+script.gem :ZenTest ,'4.5.0'
+script.gem :rspec, '1.3.1'
+#script.gem :'cucumber-rails', '0.3.2'
+#script.gem :cucumber, '1.1.8'
+script.gem :culerity, '0.2.15'
+
+script.gem :capybara, '0.3.9'
+script.gem :spork #, '0.8.5'
+script.gem :database_cleaner
+script.gem :redgreen
+script.gem :'rspec-rails', '1.3.3'
+script.gem :timecop
+script.gem :thin
+script.gem :mysql
+
+script.gem :bundler
+
+if RUBY_VERSION =~ /^1\.8\./
+  script.gem :system_timer
+  script.gem :rcov
+else
+  script.gem :simplecov
+end
+
+script.gem "bundle install --system"
+
+script.gem :cucumber, '-1.1.9'
+script.gem :gherkin, '-2.9.3'
+
+script.gem "
+    DUPLICATES=`gem list | grep -v '^rake ' | grep -v '^rack ' | grep , | wc -l`
+    if [[ \"$DUPLICATES\" != \"0\" ]]; then
+      echo 'Duplicate gems! Aborting installation'
+      gem list | grep ,
       exit
     fi
+"
+script.rvm "./script/generate cucumber --skip --spork"
 
-    echo "create database redmine character set utf8;" | mysql -u root -p$DBROOTPW mysql
-    echo "create user '$DBUSER'@'localhost' identified by '$DBPW';" | mysql -u root -p$DBROOTPW mysql
-    rm -rf ~/redmine/redmine
-    cd ~/redmine
-    #git clone git://github.com/edavis10/redmine.git
-    svn co http://redmine.rubyforge.org/svn/tags/$RMVERSION redmine
-    cd ~/redmine/redmine
-    #git fetch --tags
-    #git checkout $VERSION
-    cp ~/redmine/setup/database-redmine.yml ~/redmine/redmine/config/database.yml
-    ln -s ~/redmine/redmine_backlogs ~/redmine/redmine/vendor/plugins
-    ln -s ~/redmine/redmine_backlogs/features ~/redmine/redmine
-    echo 'rvm use 1.9.3@redmine' > ~/redmine/redmine/.rvmrc
-  
-    if [[ $RVM =~ [Yy] ]]; then
-      cd ~/redmine/redmine
-      sed -i -e"s/gem 'capybara'/gem 'capybara', '=0.3.9'/" Gemfile
-      redmine_dev=true bundle install
-    fi
+script.database "mysqladmin -f -u root -p#{Options.rootpw} drop #{Options.platform}"
+script.database "echo \"create database #{Options.platform} character set utf8;\" | mysql -u root -p#{Options.rootpw} mysql"
+script.database "echo \"create user '#{Options.user}'@'localhost' identified by '#{Options.pw}';\" | mysql -u root -p#{Options.rootpw} mysql"
+script.database "echo \"grant all privileges on redmine.* to 'redmine'@'localhost';\" | mysql -u root -p#{Options.rootpw} mysql"
+if exists("~/redmine/setup/#{Options.platform}.sql.gz")
+  script.database "zcat ~/redmine/setup/#{Options.platform}.sql.gz | mysql -u root -p#{Options.rootpw} #{Options.platform}"
+  script.database "echo \"update users set auth_source_id = NULL;\" | mysql -u root -p#{Options.rootpw} #{Options.platform}"
+end
 
-    [ -f ~/redmine/redmine/config/environments/cucumber.rb ] || script/generate cucumber --spork
-  fi
-fi
+script.database "rake db:migrate"
+script.database "bundle exec rake generate_session_store"
+script.database "REDMINE_LANG=en rake redmine:load_default_data"
+script.database "rake db:migrate:plugins"
+script.database "labels=no story_trackers=Story task_tracker=Task rake redmine:backlogs:install"
 
-# chiliproject
-if [ "$GEMSET" = "chiliproject" ]; then
-  if [ ! -f ~/redmine/chiliproject/config/database.yml ]; then
-    echo Forced CP install
-    CPINSTALL=Y
-  elif [ -z "$CPINSTALL" ]; then
-    read -p "Reinstall ChiliProject? " CP
-  fi
-  if [[ $CPINSTALL =~ [Yy] ]]; then
-    if [ -z "$CPVERSION" ]; then
-      echo "VERSION not set"
-      exit
-    fi
+if Options.admin.to_s == ''
+  script.database "cd ~/redmine/#{Options.platform}"
+  script.database "./script/runner \"User.find(:all).reject{|user| user.login.to_s == ''}.each{|user| user.password, user.password_confirmation = '$USERPW'; user.auth_source = nil; user.save!; puts '** password for ' + user.login + ' set to $USERPW'}\""
+end
 
-    echo "create database chiliproject character set utf8;" | mysql -u root -p$DBROOTPW mysql
-    echo "create user '$DBUSER'@'localhost' identified by '$DBPW';" | mysql -u root -p$DBROOTPW mysql
-    rm -rf ~/redmine/chiliproject
-    cd ~/redmine
-    git clone http://github.com/chiliproject/chiliproject.git
-    cd ~/redmine/chiliproject
-    git fetch --tags
-    git checkout v$CPVERSION
-    cp ~/redmine/setup/database-chiliproject.yml ~/redmine/chiliproject/config/database.yml
-    ln -s ~/redmine/redmine_backlogs ~/redmine/chiliproject/vendor/plugins
-    ln -s ~/redmine/redmine_backlogs/features ~/redmine/chiliproject
-    echo 'rvm use 1.8.7@chiliproject' > ~/redmine/chiliproject/.rvmrc
-  fi
-
-  if [[ $RVM =~ [Yy] ]]; then
-    cd ~/redmine/chiliproject
-    sed -i -e"s/gem 'capybara'/gem 'capybara', '=0.3.9'/" Gemfile
-    redmine_dev=true bundle install
-  fi
-
-  if [[ $CPINSTALL =~ [Yy] ]]; then
-    [ -f ~/redmine/redmine/config/environments/cucumber.rb ] || script/generate cucumber --spork
-  fi
-fi
-
-# RM database
-if [ "$GEMSET" = "redmine" ]; then
-  if [ -z "$RMDB" ]; then
-    read -p "Reinstall RM database? " RMDB
-  fi
-  if [[ $RMDB =~ [Yy] ]]; then
-    mysqladmin -f -u root -p$DBROOTPW drop redmine
-    echo "create database redmine character set utf8;" | mysql -u root -p$DBROOTPW mysql
-    echo "create user '$DBUSER'@'localhost' identified by '$DBPW';" | mysql -u root -p$DBROOTPW mysql
-    echo "grant all privileges on redmine.* to 'redmine'@'localhost';" | mysql -u root -p$DBROOTPW mysql
-  
-    cd ~/redmine/redmine
-  
-    if [ -f ~/redmine/setup/redmine.sql.gz ]; then
-      echo 'Restoring database backup'
-      zcat ~/redmine/setup/redmine.sql.gz | mysql -u root -p$DBROOTPW redmine
-      echo "update users set auth_source_id = NULL;" | mysql -u root -p$DBROOTPW redmine
-    fi
-  
-    echo "Let's go!"
-    rake db:migrate
-    rake generate_session_store
-    rake redmine:load_default_data REDMINE_LANG=en
-    rake db:migrate:upgrade:plugin_migrations
-    rake db:migrate:plugins
-    rake redmine:backlogs:install labels=no story_trackers=Story task_tracker=Task
-  
-    if [ ! -z "$USERPW" ]; then
-      ./script/runner "User.find(:all).reject{|user| user.login.to_s == ''}.each{|user| user.password, user.password_confirmation = '$USERPW'; user.auth_source = nil; user.save!; puts '** password for ' + user.login + ' set to $USERPW'}"
-    fi
-  fi
-fi
-
-if [ "$GEMSET" = "chiliproject" ]; then
-  if [ -z "$CPDB" ]; then
-    read -p "Reinstall CP database? " CPDB
-  fi
-  if [[ $CPDB =~ [Yy] ]]; then
-    mysqladmin -u root -p$DBROOTPW drop chiliproject
-    echo "create database chiliproject character set utf8;" | mysql -u root -p$DBROOTPW mysql
-    echo "create user '$DBUSER'@'localhost' identified by '$DBPW';" | mysql -u root -p$DBROOTPW mysql
-    echo "grant all privileges on chiliproject.* to 'redmine'@'localhost';" | mysql -u root -p$DBROOTPW mysql
-  
-    cd ~/redmine/chiliproject
-  
-    if [ -f ~/redmine/setup/chiliproject.sql.gz ]; then
-      echo 'Restoring database backup'
-      zcat ~/redmine/setup/chiliproject.sql.gz | mysql -u root -p$DBROOTPW chiliproject
-      echo "update users set auth_source_id = NULL;" | mysql -u root -p$DBROOTPW chiliproject
-    fi
-  
-    echo "Let's go!"
-    bundle exec rake db:migrate
-    bundle exec rake generate_session_store
-    bundle exec rake redmine:load_default_data
-    bundle exec rake db:migrate:upgrade_plugin_migrations
-    bundle exec rake db:migrate:plugins
-    bundle exec rake redmine:backlogs:install
-  
-    if [ ! -z "$ADMINPW" ]; then
-      bundle exec script/runner "user = User.find(:first, :conditions => {:admin => true}) ; user.password, user.password_confirmation = '$ADMINPW'; user.auth_source = nil; user.save!; puts '** password for ' + user.login + ' set to $ADMINPW'"
-    fi
-  fi
-fi
+puts script
